// Configuration and constants
export const CONFIG = {
  SEQUENCE_STEPS: ["warmup", "connect", "chatting", "cta", "interest", "converted"],
  CLOSURE_REASONS: ["please stop", "not interested", "irrelevant", "other"],
  DEBOUNCE_DELAY: 1000,
  MESSAGE_TIMEOUT: 2000,
  SPREADSHEET_ID_REGEX: /^[a-zA-Z0-9-_]{44}$/,
  URL_PATTERNS: [/\/spreadsheets\/d\/([a-zA-Z0-9-_]{44})/, /[?&]id=([a-zA-Z0-9-_]{44})/, /([a-zA-Z0-9-_]{44})/],
  SPREADSHEET_HEADERS: [
    "Name",
    "LinkedIn Profile URL",
    "Company",
    "Role/Title",
    "Cohort",
    "Warmup",
    "Warmup Timestamp",
    "Connect",
    "Connect Timestamp",
    "Chatting",
    "Chatting Timestamp",
    "CTA",
    "CTA Timestamp",
    "Interest",
    "Interest Timestamp",
    "Converted",
    "Converted Timestamp",
    "Date Added",
    "Notes",
    "Type",
    "Closed",
    "Closure Reason",
  ],
}
